#include "Crypto_Cfg.h"
#include "Csm_Types.h"
#include "Det.h"






uint8 ElementsData[TotalKeyElementsDataSize];
KeyElementType KeyElementsDataRef[] ={{3,19,CRYPTO_KE_RANDOM_SEED_STATE},//RNG
 {20,44,CRYPTO_KE_CIPHER_KEY_MATRIAL},{45,52,CRYPTO_KE_CIPHER_IV},{},{}//3des
,{53,69,CRYPTO_KE_CIPHER_KEY_MATRIAL},{70,86,CRYPTO_KE_CIPHER_IV},{},{}//aes128
,{87,111,CRYPTO_KE_CIPHER_KEY_MATRIAL},{112,128,CRYPTO_KE_CIPHER_IV},{},{},//aes192
{129,161,CRYPTO_KE_CIPHER_KEY_MATRIAL},{162,178,CRYPTO_KE_CIPHER_IV},{},{}, //aes256
{179,243,CRYPTO_KE_MAC_KEY},{},//hmacsha1 64
{244,264,CRYPTO_KE_MAC_KEY},{},//hmacsha1 20
{265,345,CRYPTO_KE_MAC_KEY},{},//hmacsha1 80
{355,405,CRYPTO_KE_MAC_KEY},{} //50
};
CryptoKeyElement KeyElementsCfg[KeyElementsNumber] ={
 {16,CRYPTO_KE_RANDOM_SEED_STATE,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET ,8,FALSE},//0

 {24, CRYPTO_KE_CIPHER_KEY_MATRIAL,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},//3des//1
 {8,CRYPTO_KE_CIPHER_IV,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE },{},{}, //3des

 {16, CRYPTO_KE_CIPHER_KEY_MATRIAL,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},//aes128//2
 {16,CRYPTO_KE_CIPHER_IV,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},{},{},//aes128

 {24, CRYPTO_KE_CIPHER_KEY_MATRIAL,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},//aes192//3
 {16,CRYPTO_KE_CIPHER_IV,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},{},{},//aes192

 {32, CRYPTO_KE_CIPHER_KEY_MATRIAL,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},//aes256//4
 {16,CRYPTO_KE_CIPHER_IV,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},{},{}, //aes256

 {64,CRYPTO_KE_MAC_KEY,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},{}, //hmacsha1 64//5
 {20,CRYPTO_KE_MAC_KEY,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},{}, //hmacsha1 20//6
 {80,CRYPTO_KE_MAC_KEY,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},{}, //hmacsha1 80//7
 {50,CRYPTO_KE_MAC_KEY,CRYPTO_RA_ALLOWED,CRYPTO_WA_ALLOWED,CRYPTO_KE_FORMAT_BIN_OCTET,8,FALSE},{}, //hmacsha1 50//8
};

KeyType KeyElementRef[KeysNumber] ={{0,0,1,0,FALSE,FALSE},//0
                                    {1,4,2,0,FALSE,FALSE},//1
                                    {5,8,3,0,FALSE,FALSE},//2
                                    {9,12,4,0,FALSE,FALSE},//3
                                    {13,16,5,0,FALSE,FALSE},//4
                                    {17,18,6,0,FALSE,FALSE},//5
                                    {19,20,7,0,FALSE,FALSE},//6
                                    {21,22,8,0,FALSE,FALSE},//7
                                    {23,24,9,0,FALSE,FALSE},//8
                                    {25,26,10,0,FALSE,FALSE}//9
};
